"""Client protocol and response models for the MEGA-Code API.

All models use Pydantic with no server-side dependencies.
Pipeline output models (PendingSkillData, etc.) are defined here
to keep the client package self-contained and installable standalone.
"""

from __future__ import annotations

__all__ = [
    "ACTIVE_STATUSES",
    "ERROR_STATUSES",
    "TERMINAL_STATUSES",
    "ActivePipelineItem",
    "ActivePipelinesResult",
    "BundleFile",
    "EnhanceSkillResult",
    "MegaCodeBaseClient",
    "OutputsResult",
    "PendingLessonData",
    "PendingSkillData",
    "PendingStrategyData",
    "PipelineStatusResult",
    "PipelineStopResult",
    "ProfileResult",
    "ResourcePlan",
    "SkillArtifactData",
    "SkillBundle",
    "SkillBundleError",
    "SkillRefItem",
    "TriggerPipelineResult",
    "UploadResult",
    "UserProfile",
    "ValidationFinding",
]

import zipfile
from pathlib import Path, PurePosixPath
from typing import Literal, Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field, field_validator

from mega_code.client.models import TurnSet

# =============================================================================
# Pipeline Run Status Constants
# =============================================================================
# All valid statuses: queued → running → completed | failed | timeout | stopped
#
# These sets are the single source of truth for status classification.
# Use them instead of inline tuples to keep poll loops, queries, and
# branch logic consistent when new statuses are added.

TERMINAL_STATUSES: frozenset[str] = frozenset({"completed", "failed", "timeout", "stopped"})
"""Pipeline is done — poll loops should exit."""

ACTIVE_STATUSES: frozenset[str] = frozenset({"queued", "running"})
"""Pipeline is in progress — used for conflict checks and active-run queries."""

ERROR_STATUSES: frozenset[str] = frozenset({"failed", "timeout"})
"""Pipeline finished with an error — client should report the error field."""

# =============================================================================
# Pipeline Output Models (inlined from pipeline/store/base.py)
# =============================================================================


class PendingSkillData(BaseModel):
    """Data for a pending skill awaiting user review."""

    skill_name: str
    skill_md: str = Field(description="SKILL.md content")
    injection_rules: str = Field(description="JSON string of InjectionRules")
    evidence: str = Field(description="JSON string of evidence array")
    metadata: str = Field(description="JSON string of metadata dict")
    installed: bool = False
    approved: bool = False
    author: str = ""
    version: str = ""
    tags: list[str] = Field(default_factory=list)
    skill_bundle: SkillBundle | None = Field(
        default=None,
        description=(
            "Progressive-disclosure bundle (B7). Populated when the pipeline emits "
            "a SkillBundle alongside the legacy fields; None for pre-bundle rows."
        ),
    )


class SkillArtifactData(BaseModel):
    """Data for a generated skill artifact (pipeline output)."""

    skill_id: str
    skill_type: str = ""
    decision: str = Field(description="PASS, MARGINAL, or FAIL")
    files: dict[str, str] = Field(default_factory=dict, description="filename -> content map")
    installed: bool = False
    approved: bool = False


class PendingStrategyData(BaseModel):
    """Data for a pending strategy awaiting user review."""

    strategy_name: str
    content: str = Field(description="Markdown content")
    category: str | None = None
    installed: bool = False
    approved: bool = False
    author: str = ""
    version: str = ""
    tags: list[str] = Field(default_factory=list)


class PendingLessonData(BaseModel):
    """Data for a lesson document generated by the pipeline.

    IMPORTANT: Mirrored in mega_code.server.models.PendingLessonData.
    Keep both definitions in sync — they are separate to avoid importing
    server-side models in client code (same pattern as PendingSkillData).
    """

    slug: str
    title: str
    rendered_md: str = Field("", description="Rendered markdown content")
    run_id: str | None = None
    project_id: str | None = None
    author: str = ""
    version: str = ""
    tags: list[str] = Field(default_factory=list)


# =============================================================================
# Skill Bundle Models (progressive-disclosure SKILL packaging)
# =============================================================================
# All new fields must be optional-defaulted — future additions are wire-additive only.

BundleKind = Literal["reference", "script", "asset"]


class BundleFile(BaseModel):
    """A single file packaged inside a SkillBundle (reference, script, or asset).

    Frozen so bundle contents are rewritten rather than mutated in place — catches
    accidental aliasing between pending, approved, and installed copies.
    """

    model_config = ConfigDict(frozen=True)

    path: str = Field(description="Relative forward-slash path, e.g. 'references/examples.md'")
    kind: BundleKind
    content: str = Field(description="File contents — text only in Phase 3 (D1)")

    @field_validator("path")
    @classmethod
    def _reject_escaping_path(cls, v: str) -> str:
        # Block absolute paths and any '..' segment so a malicious or
        # misconfigured server response cannot escape the bundle root when
        # write_resources joins target_dir / bf.path.
        p = PurePosixPath(v)
        if not v or p.is_absolute() or ".." in p.parts:
            raise ValueError(f"bundle file path must be relative with no '..' segments: {v!r}")
        return v


class ResourcePlan(BaseModel):
    """Planner output describing which optional bundle resources to create."""

    create_references: bool = False
    create_scripts: bool = False
    create_assets: bool = False
    rationale: str = Field(
        default="", description="One-paragraph justification with evidence citations"
    )
    planned_files: list[BundleFile] = Field(default_factory=list)


_BUNDLE_KIND_SUBDIR: dict[BundleKind, str] = {
    "reference": "references",
    "script": "scripts",
    "asset": "assets",
}

_BUNDLE_SUBDIRS: tuple[str, ...] = tuple(_BUNDLE_KIND_SUBDIR.values())

# Single source of truth for the string-backed JSON system files written beside
# SKILL.md: (filename, SkillBundle attr, on-read default when the file is absent).
# Drives the read path in from_disk / from_zip; resource_plan.json is handled
# separately because it (de)serialises through the ResourcePlan model.
_JSON_SYSTEM_FILES: tuple[tuple[str, str, str], ...] = (
    ("injection.json", "injection_rules", "{}"),
    ("evidence.json", "evidence", "[]"),
    ("metadata.json", "metadata", "{}"),
)

# All reserved root-level system filenames (the JSON sidecars + the plan).
# Consumers that need to recognise wisdom-gen system files — e.g. the remote
# packager's upload skip-list — derive from this rather than re-hardcoding names.
_SYSTEM_FILES: tuple[str, ...] = (
    *(name for name, _attr, _default in _JSON_SYSTEM_FILES),
    "resource_plan.json",
)


class SkillBundleError(ValueError):
    """Raised by SkillBundle.from_disk / from_zip for structural errors.

    The `code` field carries a stable error identifier (e.g.
    `E010_MISSING_RESOURCE_PLAN`); the `path` field is set when the error is
    scoped to a single file inside the bundle directory.
    """

    def __init__(self, code: str, message: str, *, path: str | None = None):
        self.code = code
        self.path = path
        super().__init__(f"{code}: {message}")


class SkillBundle(BaseModel):
    """A self-contained extracted skill: lean SKILL.md + optional bundled resources."""

    # Identity
    skill_slug: str = Field(description="Kebab-case canonical slug")
    version: str = "1.0.0"

    # Core instruction
    skill_md: str = Field(description="Lean SKILL.md body with frontmatter")

    # System artifacts — JSON strings, opaque to the bundle
    injection_rules: str = Field(description="JSON(InjectionRules)")
    evidence: str = Field(description="JSON(list[Evidence])")
    metadata: str = Field(description="JSON(dict)")

    # Optional bundled resources — progressive disclosure
    bundle_files: list[BundleFile] = Field(default_factory=list)

    # Plan that produced bundle_files (for audit / re-generation)
    resource_plan: ResourcePlan = Field(default_factory=ResourcePlan)

    # Review state
    installed: bool = False
    approved: bool = False
    author: str = ""
    tags: list[str] = Field(default_factory=list)

    # -- Disk I/O ------------------------------------------------------------

    def to_disk(self, base_dir: Path, *, run_id: str = "") -> Path:
        """Write the bundle into `base_dir`, returning the bundle root path.

        Layout:
            <base_dir>[/<run_id>]/<skill_slug>/
              SKILL.md
              injection.json
              evidence.json
              metadata.json
              resource_plan.json
              references/*.md    (only if bundle has references)
              scripts/*.{py,sh}  (only if bundle has scripts)
              assets/*           (only if bundle has assets)

        Empty optional sub-directories are never created.
        """
        bundle_root = Path(base_dir)
        if run_id:
            bundle_root = bundle_root / run_id
        bundle_root = bundle_root / self.skill_slug
        bundle_root.mkdir(parents=True, exist_ok=True)

        (bundle_root / "SKILL.md").write_text(self.skill_md, encoding="utf-8")
        (bundle_root / "injection.json").write_text(self.injection_rules, encoding="utf-8")
        (bundle_root / "evidence.json").write_text(self.evidence, encoding="utf-8")
        (bundle_root / "metadata.json").write_text(self.metadata, encoding="utf-8")
        self.write_resources(bundle_root)

        return bundle_root

    def write_resources(self, target_dir: Path) -> None:
        """Write resource_plan.json and bundle files into `target_dir`.

        The progressive-disclosure half of the bundle, split out so callers that
        have already materialized SKILL.md/injection/evidence/metadata (e.g. the
        remote pending writer) can add the resources without re-nesting under a
        `<slug>/` subdir. Writing resource_plan.json alongside any sub-dirs keeps
        the result loadable by `from_disk` (E010 requires a plan when sub-dirs exist).
        """
        target_dir = Path(target_dir)
        (target_dir / "resource_plan.json").write_text(
            self.resource_plan.model_dump_json(indent=2), encoding="utf-8"
        )
        target_resolved = target_dir.resolve()
        for bf in self.bundle_files:
            file_path = (target_dir / bf.path).resolve()
            if not file_path.is_relative_to(target_resolved):
                raise SkillBundleError(
                    "E030_PATH_ESCAPE",
                    f"bundle file path escapes target dir: {bf.path!r}",
                    path=bf.path,
                )
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(bf.content, encoding="utf-8")

    @classmethod
    def from_disk(cls, bundle_dir: Path) -> SkillBundle:
        """Load a bundle from `bundle_dir`. Structural-only validation.

        Applies the MQ5 archive rule:
          - no `resource_plan.json` and no bundle sub-dirs → `ResourcePlan()`
          - no `resource_plan.json` but bundle sub-dirs present → raise
            `E010_MISSING_RESOURCE_PLAN`
          - `resource_plan.json` present → normal load
        """
        bundle_dir = Path(bundle_dir)
        skill_md_path = bundle_dir / "SKILL.md"
        if not skill_md_path.is_file():
            raise SkillBundleError(
                "E020_MISSING_SKILL_MD",
                f"SKILL.md not found in {bundle_dir}",
            )

        plan_path = bundle_dir / "resource_plan.json"
        has_plan = plan_path.is_file()
        has_subdirs = any((bundle_dir / sub).is_dir() for sub in _BUNDLE_SUBDIRS)

        if not has_plan and has_subdirs:
            raise SkillBundleError(
                "E010_MISSING_RESOURCE_PLAN",
                f"Bundle sub-directories present but {plan_path.name} is missing",
            )

        plan_raw = plan_path.read_text(encoding="utf-8") if has_plan else None
        resource_plan = _parse_resource_plan(plan_raw, source_name=plan_path.name)

        bundle_files: list[BundleFile] = []
        for kind, sub in _BUNDLE_KIND_SUBDIR.items():
            sub_dir = bundle_dir / sub
            if not sub_dir.is_dir():
                continue
            for file_path in sorted(p for p in sub_dir.rglob("*") if p.is_file()):
                rel = file_path.relative_to(bundle_dir).as_posix()
                bundle_files.append(
                    BundleFile(
                        path=rel,
                        kind=kind,
                        content=file_path.read_text(encoding="utf-8"),
                    )
                )

        return cls(
            skill_slug=bundle_dir.name,
            skill_md=skill_md_path.read_text(encoding="utf-8"),
            bundle_files=bundle_files,
            resource_plan=resource_plan,
            **{
                attr: _read_or_default(bundle_dir / name, default)
                for name, attr, default in _JSON_SYSTEM_FILES
            },
        )

    # -- ZIP I/O -------------------------------------------------------------

    def to_zip(self, path: Path) -> Path:
        """Write the bundle as a flat-rooted ZIP archive (no `<slug>/` wrapper)."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("SKILL.md", self.skill_md)
            zf.writestr("injection.json", self.injection_rules)
            zf.writestr("evidence.json", self.evidence)
            zf.writestr("metadata.json", self.metadata)
            zf.writestr("resource_plan.json", self.resource_plan.model_dump_json(indent=2))
            for bf in self.bundle_files:
                zf.writestr(bf.path, bf.content)
        return path

    @classmethod
    def from_zip(cls, path: Path, *, skill_slug: str | None = None) -> SkillBundle:
        """Load a bundle from a flat-rooted ZIP archive.

        Since flat-rooted ZIPs carry no `<slug>/` wrapper, `skill_slug` must
        be supplied; when omitted, the ZIP filename stem is used.
        """
        path = Path(path)
        slug = skill_slug if skill_slug is not None else path.stem
        with zipfile.ZipFile(path, "r") as zf:
            names = set(zf.namelist())
            if "SKILL.md" not in names:
                raise SkillBundleError(
                    "E020_MISSING_SKILL_MD",
                    f"SKILL.md not found at archive root of {path}",
                )

            has_plan = "resource_plan.json" in names
            has_subdir_entries = any(
                name.split("/", 1)[0] in _BUNDLE_SUBDIRS for name in names if "/" in name
            )
            if not has_plan and has_subdir_entries:
                raise SkillBundleError(
                    "E010_MISSING_RESOURCE_PLAN",
                    "Bundle sub-directories present but resource_plan.json is missing",
                )

            plan_raw = zf.read("resource_plan.json").decode("utf-8") if has_plan else None
            resource_plan = _parse_resource_plan(plan_raw, source_name="resource_plan.json")

            bundle_files: list[BundleFile] = []
            for kind, sub in _BUNDLE_KIND_SUBDIR.items():
                prefix = sub + "/"
                for name in sorted(
                    n for n in names if n.startswith(prefix) and not n.endswith("/")
                ):
                    bundle_files.append(
                        BundleFile(
                            path=name,
                            kind=kind,
                            content=zf.read(name).decode("utf-8"),
                        )
                    )

            return cls(
                skill_slug=slug,
                skill_md=zf.read("SKILL.md").decode("utf-8"),
                bundle_files=bundle_files,
                resource_plan=resource_plan,
                **{
                    attr: _zip_read_or_default(zf, names, name, default)
                    for name, attr, default in _JSON_SYSTEM_FILES
                },
            )

    # -- Adapter -------------------------------------------------------------

    @classmethod
    def from_pending_skill_data(cls, pend: PendingSkillData) -> SkillBundle:
        """Adapt a legacy `PendingSkillData` into an empty-plan `SkillBundle`.

        Maps `skill_name → skill_slug` via the client-side canonical slug
        derivation. `bundle_files` and `resource_plan` start empty —
        progressive disclosure is opt-in.
        """
        # Late import to avoid a skill_utils → protocol cycle.
        from mega_code.client.skill_utils import canonical_skill_name

        return cls(
            skill_slug=canonical_skill_name(pend.skill_name, pend.skill_md),
            version=pend.version or "1.0.0",
            skill_md=pend.skill_md,
            injection_rules=pend.injection_rules,
            evidence=pend.evidence,
            metadata=pend.metadata,
            installed=pend.installed,
            approved=pend.approved,
            author=pend.author,
            tags=list(pend.tags),
        )


def _parse_resource_plan(raw: str | None, *, source_name: str) -> ResourcePlan:
    """Parse resource_plan.json text, or return an empty plan when ``raw`` is None.

    Callers pass None when the bundle has no resource_plan.json (the MQ5 archive
    rule — sub-dirs present without a plan — is enforced before this point).
    """
    if raw is None:
        return ResourcePlan()
    try:
        return ResourcePlan.model_validate_json(raw)
    except ValueError as exc:
        raise SkillBundleError(
            "E010_MISSING_RESOURCE_PLAN",
            f"Failed to parse {source_name}: {exc}",
        ) from exc


def _read_or_default(path: Path, default: str) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return default


def _zip_read_or_default(zf: zipfile.ZipFile, names: set[str], name: str, default: str) -> str:
    if name in names:
        return zf.read(name).decode("utf-8")
    return default


PendingSkillData.model_rebuild()


class ValidationFinding(BaseModel):
    """A single finding from validate_bundle / validate_frontmatter.

    Shared type — frontmatter findings carry F-prefixed codes, bundle findings
    carry E/W codes, planner findings P-prefixed. Severity (not type) distinguishes
    blockers from warnings.
    """

    code: str = Field(description="e.g. 'E002_SKILL_MD_TOO_LONG', 'F001_MISSING_REQUIRED_KEY'")
    severity: Literal["error", "warning"]
    message: str
    path: str | None = Field(
        default=None, description="e.g. 'references/api.md' when the finding is path-scoped"
    )


# =============================================================================
# Response Models
# =============================================================================


class UploadResult(BaseModel):
    """Result of uploading trajectory data."""

    status: str = Field("accepted", description="Upload status")
    session_id: str = Field("", description="Session UUID")
    message: str = Field("", description="Human-readable message")


class OutputsResult(BaseModel):
    """Pipeline outputs for a project run."""

    skill_artifacts: list[SkillArtifactData] = Field(default_factory=list)
    pending_skills: list[PendingSkillData] = Field(default_factory=list)
    pending_strategies: list[PendingStrategyData] = Field(default_factory=list)
    pending_lessons: list[PendingLessonData] = Field(default_factory=list)
    skill_bundles: list[SkillBundle] = Field(
        default_factory=list,
        description=(
            "Progressive-disclosure bundles (B7). Wire carrier for SkillBundle "
            "objects emitted by the pipeline. Empty list for pre-bundle runs."
        ),
    )


class TriggerPipelineResult(BaseModel):
    """Result of triggering a pipeline run."""

    run_id: str = Field(..., description="Unique pipeline run ID")
    status: str = Field("queued", description="Initial status")
    message: str = Field("", description="Human-readable message")


class PipelineStatusResult(BaseModel):
    """Status of a pipeline run."""

    run_id: str
    project_id: str
    status: str
    started_at: str | None = None
    completed_at: str | None = None
    progress: dict | None = None
    outputs: OutputsResult | None = None
    report: dict | None = None
    error: str | None = None


class UserProfile(BaseModel):
    """User profile for personalization.

    Fields language/level/style are set via CLI. Fields eureka/goals/enabled/autoPermission
    are shared with the MegaEureka VSCode extension.
    """

    language: str | None = Field(None, description="Preferred language (e.g. English, Thai)")
    level: str | None = Field(None, description="Experience level (Beginner, Intermediate, Expert)")
    style: str | None = Field(None, description="Teaching style (Mentor, Formal, Concise)")
    eureka: bool = Field(True, description="[MegaEureka] Enable learning cards generation")
    goals: list[str] = Field(
        default_factory=list, description="[MegaEureka] Learning goals for personalized content"
    )
    enabled: bool = Field(True, description="[MegaEureka] Master switch for personalization")
    auto_permission: bool = Field(
        False,
        alias="autoPermission",
        description="[MegaEureka] Auto-approve bash permissions in hooks",
    )
    email: str | None = Field(
        None,
        description="Authenticated user's email. Server-populated, read-only on client.",
    )

    model_config = ConfigDict(populate_by_name=True)


class ProfileResult(BaseModel):
    """Result of saving a profile."""

    success: bool = Field(True, description="Whether profile was saved")
    message: str = Field("", description="Human-readable message")


class EnhanceSkillResult(BaseModel):
    """Result of updating a skill with enhanced content."""

    success: bool = Field(True, description="Whether skill was enhanced")
    message: str = Field("", description="Human-readable message")


class PipelineStopResult(BaseModel):
    """Result of stopping a pipeline run."""

    run_id: str
    status: str
    message: str = ""


class ActivePipelineItem(BaseModel):
    """Summary of a single active pipeline run (client-side)."""

    run_id: str
    project_id: str
    status: str
    started_at: str | None = None
    progress: dict | None = None


class ActivePipelinesResult(BaseModel):
    """List of active pipeline runs for the authenticated user."""

    active: bool = False
    runs: list[ActivePipelineItem] = Field(default_factory=list)


# =============================================================================
# Wisdom Curate (PCR Skill Networking)
# =============================================================================


class WisdomResultItem(BaseModel):
    """Single wisdom item from curate results."""

    wisdom_id: str = Field(description="Unique identifier of the wisdom record")
    score: float = Field(description="Relevance score from the wisdom graph")
    is_seed: bool = Field(default=False, description="Whether this wisdom is a seed node")


class SkillRefItem(BaseModel):
    """Reference to a curated skill file."""

    name: str = Field(description="Skill name derived from the wisdom graph")
    path: str = Field(description="Relative path to the skill file within the ZIP")
    url: str = Field(default="", description="Pre-signed URL to download the skill ZIP")


class ServedWisdomItem(BaseModel):
    """Served wisdom metadata for NL feedback session recovery."""

    wisdom_id: str = Field(description="Wisdom identifier")
    description: str = Field(default="", description="Wisdom description")
    combined_score: float = Field(description="Similarity score used for transfer curves")
    stage: str = Field(description="PCR stage (e.g. diagnosis, implementation)")
    step_id: str = Field(description="Step identifier in the curation workflow")


class WisdomCurateResult(BaseModel):
    """Result from wisdom curate endpoint."""

    session_id: str = Field(description="Session identifier for linking feedback")
    query: str = Field(description="Original user query")
    curation: str = Field(description="Markdown curation document with step-by-step workflow")
    skills: list[SkillRefItem] = Field(default_factory=list, description="Curated skill references")
    wisdoms: list[WisdomResultItem] = Field(
        default_factory=list, description="Retrieved wisdom records with scores"
    )
    served_wisdoms: list[ServedWisdomItem] = Field(
        default_factory=list, description="Served wisdom metadata for feedback session recovery"
    )
    token_count: int = Field(default=0, description="Total LLM tokens consumed")
    cost_usd: float = Field(default=0.0, description="Total LLM cost in USD")


class WisdomFeedbackResult(BaseModel):
    """Result from wisdom feedback endpoint."""

    session_id: str = Field(description="Session identifier from the curate call")
    feedback_id: str = Field(description="Unique identifier for the submitted feedback")
    status: str = Field(default="saved", description="Feedback submission status")


# Client Protocol
# =============================================================================


@runtime_checkable
class MegaCodeBaseClient(Protocol):
    """Client protocol for interacting with the MEGA-Code system.

    Implementations:
    - MegaCodeRemote: HTTP client to a MEGA-Code FastAPI server
    - MegaCodeLocal: In-process implementation for server-side use
    """

    def upload_trajectory(
        self,
        *,
        turn_set: TurnSet,
        project_id: str,
    ) -> UploadResult: ...

    def get_outputs(
        self,
        *,
        project_id: str,
        run_id: str,
    ) -> OutputsResult: ...

    async def trigger_pipeline_run(
        self,
        *,
        project_id: str,
        project_path: Path | None = None,
        session_id: str | None = None,
        steps: list[str] | None = None,
        force: bool = False,
        limit: int | None = None,
        concurrency: int = 64,
        model: str | None = None,
        project_cwd: str | None = None,
        agent: str = "",
    ) -> TriggerPipelineResult: ...

    def get_pipeline_status(
        self,
        *,
        run_id: str,
    ) -> PipelineStatusResult: ...

    def save_profile(
        self,
        *,
        profile: UserProfile,
    ) -> ProfileResult: ...

    def load_profile(self) -> UserProfile: ...

    def stop_pipeline(self, *, run_id: str) -> PipelineStopResult: ...

    def get_active_pipelines(self) -> ActivePipelinesResult: ...

    def enhance_skill(
        self,
        *,
        skill_name: str,
        skill_md: str,
        version: str,
        metadata: dict | None = None,
    ) -> EnhanceSkillResult: ...
